### PR TITLE
Adds NuclearCraft support to ICBM-Classic.

### PR DESCRIPTION
**Pull request by Rendman**
This change causes radiation to be added to chunks that are affected by the nuke detonation.

### CODE REVIEW

**Comment by DarkGuardsman** [comment]
The code looks good, I'll likely test this Saturday and pull it in when I get some time.

**Comment by DarkGuardsman** [comment]
Got a chance to clone down your changes and there are issues. Don't take any of the following personally, I'm happy you sent a PR but I can't pull it as it would break the mod.

A) Built scripts are not set to compile with Nuclearcraft. This will prevent ICBM from building on our CI servers. As well I could not locate a deobf or API version of Nuclearcraft. This might present an additional issue trying to get ICBM compiled correctly. This is the main problem as the rest can easily be fixed.

B) There seem to be random Nuclearcraft imports were there not needed. Blastrot for example, not a major issue but could be cleaned up.

C) We can't be calling to the proxy to check logic. This will cause issues and possible crashes in the future. The better way is to either isolate using abstraction or do a simple Loader.isModLoaded(modid) checks in another location. Normally we use a Mods enum but ICBM seems to be lacking one. If we get the other issues fixed this would be easy to solve. 

D) You can't store the proxy in BlastRot from the Instance then run an isActive check on the proxy. This could cause problems with the logic. Assuming ASM magic from FML doesn't solve it in an odd way.

As well the proxy should never be stored. Its designed to act as a loader and not something that is used. For this, you would want to make an interface and reference that in the main class somewhere... not the blast rot. 

Ignore IC2Proxy in this instance, as it's implemented improperly so shouldn't be used as a reference.

E) blockRadioactive should be assigned from the proxy and not in ICBMClassic.java. This could cause logic problems and/or crashes. 

Honestly, if you can find me a file we can use to compile against I can solve the rest of the problems after merging. I need to rework a lot of these systems to make it ready for Atomic Science support soon. Which will involve a few event calls and interface that could be used for Nuclearcraft support as well.

**Comment by Rendman** [comment]
No problem… yeah, the NuclearCraft dev does not have deobj/api JAR’s that I could find. Let me see what I can find out, ill contact the mod author directly.

**Comment by DarkGuardsman** [comment]
K thank you that will save me time having to do the same. Was going to talk to him in a week or so when I had more time. Try to see if he can set up a maven for his mod. If he needs help the devs on MMD discord could give a hand easily. https://discord.mcmoddev.com/

**Pull request closed without merging**
